op = Manga.create(name:"One Piece", genre:"shonen")
berserk = Manga.create(name:"Berserk", genre:"shonen")
Manga.create(name:"Hunter X Hunter", genre:"shonen")
Manga.create(name:"Magi", genre: "shonen")
Manga.create(name:"Breaker: New Waves", genre:"shonen")

chapter1 = op.chapters.create(chaptnum:1, manga_id:op.id)
chapter2 = op.chapters.create(chaptnum:2, manga_id:op.id)
op.chapters.create(chaptnum:3, manga_id:op.id)
op.chapters.create(chaptnum:4, manga_id:op.id)
op.chapters.create(chaptnum:5, manga_id:op.id)

chapter2.pages.create(pagenum:1, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/001.jpg")
chapter2.pages.create(pagenum:2, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/002.jpg")
chapter2.pages.create(pagenum:3, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/003.jpg")
chapter2.pages.create(pagenum:4, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/004.jpg")
chapter2.pages.create(pagenum:5, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/005.jpg")
chapter2.pages.create(pagenum:6, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/006.jpg")
chapter2.pages.create(pagenum:7, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/007.jpg")
chapter2.pages.create(pagenum:8, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/008.jpg")
chapter2.pages.create(pagenum:9, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/009.jpg")
chapter2.pages.create(pagenum:10, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/010.jpg")
chapter2.pages.create(pagenum:11, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/011.jpg")
chapter2.pages.create(pagenum:12, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/012.jpg")
chapter2.pages.create(pagenum:13, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/013.jpg")
chapter2.pages.create(pagenum:14, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/014.jpg")
chapter2.pages.create(pagenum:15, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/015.jpg")
chapter2.pages.create(pagenum:16, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/016.jpg")
chapter2.pages.create(pagenum:17, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/017.jpg")
chapter2.pages.create(pagenum:18, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/018.jpg")
chapter2.pages.create(pagenum:19, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/019.jpg")
chapter2.pages.create(pagenum:20, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/020.jpg")
chapter2.pages.create(pagenum:21, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/021.jpg")
chapter2.pages.create(pagenum:22, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/022.jpg")
chapter2.pages.create(pagenum:23, chapter_id:2, url:"https://s3-us-west-2.amazonaws.com/manatee/onepiece/chapter2/023.jpg")

bchapt1 = berserk.chapters.create(chaptnum:1, manga_id:berserk.id)
bchapt2 = berserk.chapters.create(chaptnum:2, manga_id:berserk.id)
bchapt3 = berserk.chapters.create(chaptnum:3, manga_id:berserk.id)
bchapt4 = berserk.chapters.create(chaptnum:4, manga_id:berserk.id)
bchapt5 = berserk.chapters.create(chaptnum:5, manga_id:berserk.id)
bchapt6 = berserk.chapters.create(chaptnum:6, manga_id:berserk.id)
bchapt7 = berserk.chapters.create(chaptnum:7, manga_id:berserk.id)
bchapt8 = berserk.chapters.create(chaptnum:8, manga_id:berserk.id)
bchapt9 = berserk.chapters.create(chaptnum:9, manga_id:berserk.id)

i = 0
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+cover+volume+01.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p000.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p001.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p002.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p003.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p004.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p005.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p006-07.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p008.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p009.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p010.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p011.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p012.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p013.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p014.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p015.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p016.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p017.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p018.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p019.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p020-21.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p022.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p023.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p024.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p025.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p026.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p027.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p028.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p029.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p030.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p031.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p032.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p033.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p034.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p035.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p036.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p037.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p038.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p039.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p040.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p041.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p042.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p043.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p044.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p045.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p046.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p047.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p048.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p049.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p050.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p051.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p052.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p053.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p054.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p055.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p056.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p057.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p058-59.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p060.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p061.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p062.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p063.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p064.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p065.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p066.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p067.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p068.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p069.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p070.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p071.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p072.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p073.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p074.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p075.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p076.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p077.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p078.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p079.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p080.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p081.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p082.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p083.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p084-85.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p086.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p087.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p088.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p089.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p090.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p091.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p092.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p093.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p094.jpg")
bchapt1.pages.create(pagenum:i+=1, chapter_id:bchapt1.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c01p095.jpg")


x = 0
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c02p096-097.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c02p098.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter1/Berserk+-+v01c02p099.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p100.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p101.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p102.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p103.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p104.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p105.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p106.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p107.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p108.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p109.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p110.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p111.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p112.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p113.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p114.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p115.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p116.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p117.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p118.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p119.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p120.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p121.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p122.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p123.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p124.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p125.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p126.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p127.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p128.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p129.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p130-131.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p132.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p133.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p134.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p135.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p136.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p137.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p138.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p139.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p140.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p141.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p142.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p143.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p144.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p145.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p146.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p147.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p148.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p149.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p150.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p151.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p152.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p153.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p154-155.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p156.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p157.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p158.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p159.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p160.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p161.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p162.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p163.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p164.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p165.jpg")
bchapt2.pages.create(pagenum:x+=1, chapter_id:bchapt2.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter2/Berserk+-+v01c02p166.jpg")

y=0

bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p167.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p168-169.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p170.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p171.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p172.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p173.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p174.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p175.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p176.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p177.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p178.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p179.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p180.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p181.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p182.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p183.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p184.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p185.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p186-167.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p188.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p189.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p190.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p191.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p192.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p193.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p194.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p195.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p196.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p197.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p198.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p199.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p200.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p201.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p202.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p203.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p204.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p205.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p206.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p207.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p208.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p209.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p210.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p211.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p212.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p213.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p214.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p215.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p216.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p217.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p218.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p219.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p220.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p221.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p222.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p223.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p224.jpg")
bchapt3.pages.create(pagenum:y+=1, chapter_id:bchapt3.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter3/Berserk+-+v01c03p225.jpg")

q=0

bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/cover.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_a.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_b.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p001.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p002.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p003.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p004.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p005.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p006.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p007.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p008.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p009.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p010.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p011.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p012.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p013.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p014.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p015.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p016.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p017.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p018.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p019.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p020.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p021.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p022.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p023.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p024.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p025.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p026.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p027.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p028.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p029.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p030.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p031.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p032.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p033.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p034.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p035.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p036.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p037.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p038.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p039.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p040.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p041.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p042.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p043.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p044.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p045.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p046.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p047.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p048.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p049.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p050.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p051.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p052.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p053.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p054.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p055.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p056.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p057.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p058.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p059.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p060.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p061.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p062.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p063.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p064.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p065.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p066.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p067.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p068.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p069.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p070.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p071.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p072.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p073.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p074.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p075.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p076.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p077.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p078.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p079.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p080.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p081.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p082.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p083.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p084.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p085.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p086.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p087.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p088.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p089.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p090.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p091.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p092.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p093.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p094.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p095.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p096.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p097.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p098.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p099.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p100.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p101.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p102.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p103.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p104.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p105.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p106.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p107.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p108.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p109.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p110.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p111.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p112.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p113.jpg")
bchapt4.pages.create(pagenum:q+=1, chapter_id:bchapt4.id, url:"https://s3-us-west-2.amazonaws.com/manatee/berserk/chapter4/v2_ep1_p114.jpg")












































